swagger: "2.0"
info:
  description: Приложение todo для составления и редактирования списка дел на определенный промежуток времени
  version: "1.0.0"
  title: "todo"

host: "localhost"
basePath: "/api"

schemes:
- "http"
paths:
  /todos:
    get:
      summary: "Get todo-list"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
              
    post:
      responses:
        200:
          description: "Success"
      summary: "Add a new task to the todo-list"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added to the todo-list"
        required: true
        schema:
          $ref: "#/definitions/Task"
             
  /todos/{taskId}:   
    put:
      responses:
        200:
          description: "Success"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of task to change"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added to the todo-list"
        required: true
        schema:
          $ref: "#/definitions/Task"
      summary: "Update an existing task"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      
definitions:
  Task:
    type: "object"
    required:
    - "name"
    - "status"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Repair"
      status:
        type: "string"
        description: "task status in the todo-list"
        enum:
        - "done"
        - "started"
        - "new"
 

